development:
  adapter: postgresql
  database: invisibility_cloak_db
  username: ENV["USER_NAME"]
  password: ENV["USER_PASS"]
  host: localhost

production:
  adapter: postgresql
  database: invisibility_cloak_db
  username: ENV["USER_NAME"]
  password: ENV["USER_PASS"]
  host: localhost
