INSERT INTO translations (content, type) VALUES
('Row 1', 'Row Head'),
('TextBlock', 'Row Desc'),
('<span class="text-block" style="font-size: 16px;">', 'HTML'),
('<strong>', 'HTML'),
('</strong>', 'HTML'),
('</span>', 'HTML'),
('<span style="color: rgb(0, 0, 0); font-family: Times New Roman; font-size: 16px;">', 'HTML'),
('</span>', 'HTML'),
('<strong>', 'HTML'),
('<span style="color: rgb(31, 73, 125); font-family: Arial; font-size: 16.5pt;">', 'HTML'),
('Welcome to the Hourly/Non-Management Assessment ', 'Copy'),
('<span style="color: rgb(31, 73, 125);">', 'HTML'),
('Performance ', 'Copy'),
('</span>', 'HTML'),
('Rating Survey!', 'Copy'),
('</span>', 'HTML'),
('</strong>', 'HTML'),
('<br />', 'HTML'),
('<span style="color: rgb(0, 0, 0); font-family: Times New Roman; font-size: 16px;">', 'HTML'),
('</span>', 'HTML'),
('Row 2',	'Row Head'),
('TextBlock',	'Row Desc'),
('<span class="text-block">',	'HTML'),
('<span style="font-size: 16px;">', 'HTML'),
('<strong>', 'HTML'),
('<span style="font-size: 18px;">', 'HTML'),
('<span style="color: rgb(31, 73, 125);">', 'HTML'),
('Confidentiality', 'Copy'),
('</span', 'HTML'),
('<br />', 'HTML'),
('<br />', 'HTML'),
('</span>', 'HTML'),
('</strong>', 'HTML'),
('<span style="color: rgb(0, 0, 0);">', 'HTML'),
('All', 'Copy'),
('</span>', 'HTML'),
('<span style="color: rgb(0, 0, 0);">', 'HTML'),
('responses to the survey will be strictly confidential. While your response to the survey is uniquely identifiable to you, results will be reported for groups of people, not individuals.', 'Copy'),
('&nbsp;', 'HTML'),
('Results will be consolidated by the HR Research team;', 'Copy'),
('&nbsp;', 'HTML'),
('no one other than the HR Research team at corporate headquarters will have access to or know how you responded to any question. All survey responses are transferred to and stored in the survey system located in the United States', 'Copy'),
('</span>', 'HTML'),
('<span style="color: rgb(0, 0, 0);">', 'HTML'),
('.',	'Copy'),
('</span>', 'HTML'),
('</span>', 'HTML'),
('<br />', 'HTML'),
('</span>', 'HTML')
